---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint 
    runs-on: ubuntu-20.04 
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: $({ secrets.mlouk24 })
          password: $({ secrets.dckr_pat_knXooGOSF6Z4s0AmLW06ylb9JpE })
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"